# Generated by Django 5.2.16 on 2026-08-08 14:55

import django.core.validators
import django.db.models.deletion
import recruitment.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_id", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("current_company", models.CharField(blank=True, max_length=255)),
                ("school", models.CharField(blank=True, max_length=255)),
                ("skills_text", models.TextField(blank=True)),
                ("profile", models.JSONField(blank=True, default=dict)),
                ("resume_modules", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "applicant_id"],
            },
        ),
        migrations.CreateModel(
            name="ExclusionMarker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_id", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("object_type", models.CharField(max_length=64)),
                ("object_reference", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "信息"),
                            ("success", "成功"),
                            ("warning", "警告"),
                            ("error", "错误"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField(blank=True)),
                ("target_url", models.CharField(blank=True, max_length=500)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beisen_position_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "requisition_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("name", models.CharField(max_length=255)),
                ("position_type", models.CharField(blank=True, max_length=255)),
                ("source_jd", models.TextField(blank=True)),
                ("evaluation_jd", models.TextField(blank=True)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "有效"), ("historical", "历史")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "status_source",
                    models.CharField(
                        choices=[
                            ("beisen", "北森"),
                            ("manual", "人工"),
                            ("unknown", "未知"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("manual_status_override", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("beisen_position_id", ""), _negated=True),
                        fields=("beisen_position_id",),
                        name="unique_nonempty_beisen_position_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("origin", "北森原始简历"),
                            ("standard", "北森标准简历"),
                            ("manual", "HR 补充文件"),
                        ],
                        default="origin",
                        max_length=16,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                (
                    "source_file",
                    models.FileField(
                        blank=True, upload_to=recruitment.models.resume_upload_path
                    ),
                ),
                (
                    "standard_pdf",
                    models.FileField(
                        blank=True, upload_to=recruitment.models.resume_upload_path
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "等待解析"),
                            ("parsing", "解析中"),
                            ("success", "解析成功"),
                            ("low_quality", "质量过低"),
                            ("failed", "解析失败"),
                            ("unsupported", "格式不支持"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "parse_quality",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("parse_error", models.TextField(blank=True)),
                ("protected", models.BooleanField(default=False)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_versions",
                        to="recruitment.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "application_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("beisen", "北森投递"), ("talent", "人才库推荐")],
                        default="beisen",
                        max_length=16,
                    ),
                ),
                ("source_channel", models.CharField(blank=True, max_length=255)),
                ("application_status", models.CharField(blank=True, max_length=128)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("purge_after", models.DateTimeField(blank=True, null=True)),
                ("delete_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_recommendations",
                        to="recruitment.application",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="recruitment.position",
                    ),
                ),
                (
                    "current_resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_for_applications",
                        to="recruitment.resumeversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "全量"),
                            ("incremental", "增量"),
                            ("reconciliation", "校准"),
                            ("manual", "手动"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("window_start", models.DateTimeField(blank=True, null=True)),
                ("window_end", models.DateTimeField(blank=True, null=True)),
                ("cursor", models.CharField(blank=True, max_length=255)),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="resumeversion",
            constraint=models.UniqueConstraint(
                fields=("candidate", "content_hash"),
                name="unique_candidate_resume_hash",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["position", "deleted_at"], name="recruitment_positio_d7bc3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["candidate", "source_type"],
                name="recruitment_candida_fe7a31_idx",
            ),
        ),
    ]
