# Generated by Django 5.2.16 on 2026-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_sync_job_cancellation_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="current_company",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="school",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
