# Generated by Django 5.2.16 on 2026-08-08 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recruitment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "email"), name="unique_reviewer_identity"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("email_pending", "邮件发送中"),
                            ("email_failed", "邮件发送失败"),
                            ("pending", "待审核"),
                            ("partial", "部分完成"),
                            ("completed", "已完成"),
                            ("revoked", "已撤销"),
                            ("expired", "已过期"),
                        ],
                        default="email_pending",
                        max_length=20,
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("pending", "等待"),
                            ("sent", "已发送"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("email_retry_count", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_batches",
                        to="recruitment.position",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="reviews.reviewer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PositionReviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_links",
                        to="recruitment.position",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_links",
                        to="reviews.reviewer",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "reviewer"), name="unique_position_reviewer"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "未提交"),
                            ("approved", "通过"),
                            ("rejected", "不通过"),
                            ("discuss", "待讨论"),
                            ("withdrawn", "HR 已撤回"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("is_draft", models.BooleanField(default=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_items",
                        to="recruitment.application",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reviews.reviewbatch",
                    ),
                ),
                (
                    "resume_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_items",
                        to="recruitment.resumeversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "application"),
                        name="unique_review_batch_application",
                    )
                ],
            },
        ),
    ]
