# Generated by Django 5.2.16 on 2026-08-08 14:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recruitment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=64, unique=True)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_jobs",
                        to="recruitment.position",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "等待"),
                            ("running", "分析中"),
                            ("success", "成功"),
                            ("parse_failed", "简历解析失败"),
                            ("model_error", "模型服务异常"),
                            ("cancelled", "已取消"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "force_reanalysis_reason",
                    models.CharField(blank=True, max_length=255),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_items",
                        to="recruitment.application",
                    ),
                ),
                (
                    "resume_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analysis_items",
                        to="recruitment.resumeversion",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="analysis.analysisjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("priority", "优先评估"),
                            ("review", "建议人工复核"),
                            ("low", "匹配度较低"),
                        ],
                        max_length=16,
                    ),
                ),
                ("hard_requirement_results", models.JSONField(default=list)),
                ("dimension_results", models.JSONField(default=list)),
                ("strengths", models.JSONField(default=list)),
                ("risks", models.JSONField(default=list)),
                ("missing_information", models.JSONField(default=list)),
                ("interview_focus", models.JSONField(default=list)),
                ("interview_questions", models.JSONField(default=list)),
                ("raw_response", models.JSONField(default=dict)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="analysis.analysisitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="analysisitem",
            name="reused_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reuse_items",
                to="analysis.analysisreport",
            ),
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "input_cost_per_million",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "output_cost_per_million",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "name", "version"),
                        name="unique_model_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ModelUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recruitment.position",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analysis.modelversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="model_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="analysis.modelversion"
            ),
        ),
        migrations.CreateModel(
            name="PositionRuleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "历史"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("evaluation_jd", models.TextField(blank=True)),
                ("hard_requirements", models.JSONField(blank=True, default=list)),
                ("dimensions", models.JSONField(blank=True, default=list)),
                ("bonus_items", models.JSONField(blank=True, default=list)),
                (
                    "rating_thresholds",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="默认包含 priority/review/low 三个区间。",
                    ),
                ),
                ("source_jd_snapshot", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_position_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_versions",
                        to="recruitment.position",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_position_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "-version"],
            },
        ),
        migrations.AddField(
            model_name="analysisitem",
            name="rule_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_items",
                to="analysis.positionruleversion",
            ),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="prompt_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="analysis.promptversion"
            ),
        ),
        migrations.CreateModel(
            name="ReportNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("comment", "补充说明"),
                            ("correction", "纠错备注"),
                            ("conclusion", "人工结论"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="analysis.analysisreport",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="positionruleversion",
            constraint=models.UniqueConstraint(
                fields=("position", "version"), name="unique_position_rule_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="analysisitem",
            constraint=models.UniqueConstraint(
                fields=("job", "application"), name="unique_analysis_job_application"
            ),
        ),
    ]
