# Generated by Django 5.2.16 on 2026-08-28 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_task_cancellation_statuses"),
        ("recruitment", "0004_alter_candidate_current_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisitem",
            name="rule_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analysis_items",
                to="analysis.positionruleversion",
            ),
        ),
        migrations.AlterField(
            model_name="positionruleversion",
            name="jd_decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rule_versions",
                to="recruitment.positionjddecision",
            ),
        ),
    ]
