# Generated by Django 5.2.16 on 2026-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_alter_analysisitem_rule_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelusage",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("resume_analysis", "简历分析"),
                    ("rule_draft", "规则草稿"),
                    ("jd_diff", "岗位说明差异"),
                    ("jd_merge", "岗位说明合并"),
                ],
                default="resume_analysis",
                max_length=32,
            ),
        ),
    ]
