# Generated by Django 5.2.16 on 2026-09-07 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0007_alter_modelusage_purpose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="模型接口地址"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="API Key"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="模型名称"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用覆盖"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_model_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "全局模型配置",
                "verbose_name_plural": "全局模型配置",
                "ordering": ["-updated_at"],
            },
        ),
    ]
