# Generated by Django 5.2.16 on 2026-08-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0003_sync_job_cancellation_statuses"),
        ("talent_pool", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentmembership",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="talent_memberships",
                to="recruitment.position",
                verbose_name="来源岗位",
            ),
        ),
    ]
