# Generated by Django 5.2.16 on 2026-08-21 09:31

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0004_alter_candidate_current_company_and_more"),
        ("talent_pool", "0003_backfill_talentmembership_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="talentmembership",
            options={"ordering": ["-joined_at", "-id"]},
        ),
        migrations.AlterField(
            model_name="talentmembership",
            name="joined_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="talentmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "已入库"),
                    ("stale", "资料可能过期"),
                    ("removed_pending", "已移出待恢复"),
                    ("removed", "已移出"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="talenttag",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="talentmembership",
            index=models.Index(
                fields=["status", "-joined_at", "-id"], name="talent_status_joined_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="talenttagassignment",
            index=models.Index(
                fields=["tag", "membership"], name="talent_tag_assign_idx"
            ),
        ),
    ]
