# Generated by Django 5.2.16 on 2026-08-31 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0004_alter_candidate_current_company_and_more"),
        ("talent_pool", "0004_alter_talentmembership_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewResultOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("color", models.CharField(default="default", max_length=32)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TalentInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_name",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "interview_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("interview_time", models.CharField(blank=True, max_length=32)),
                (
                    "first_interviewer",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "second_interviewer",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "result",
                    models.CharField(db_index=True, default="未面试", max_length=64),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "channel",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.candidate",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="talent_pool.talentmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["-interview_date", "-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-interview_date", "-created_at"],
                        name="talent_interview_date_idx",
                    )
                ],
            },
        ),
    ]
