# Generated by Django 5.2.16 on 2026-09-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talent_pool", "0005_interviewresultoption_talentinterview"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentinterview",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
